const $=s=>document.querySelector(s);let selected=null,sessions=[];
const api=async(path,options={})=>{const r=await fetch(path,{headers:{"Content-Type":"application/json"},...options});if(!r.ok)throw new Error((await r.json()).detail||r.statusText);return r.json()};
const escapeHtml=s=>String(s??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
const toast=msg=>{const t=$("#toast");t.textContent=msg;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),2200)};
async function load(){try{[sessions,metrics]=await Promise.all([api("/api/sessions"),api("/api/metrics")]);renderSessions();renderMetrics(metrics);if(selected)await selectSession(selected)}catch(e){toast(e.message)}}
function renderMetrics(m){$("#activeMetric").textContent=m.active_sessions;$("#liveBadge").textContent=m.active_sessions;$("#signalMetric").textContent=m.techniques;$("#latencyMetric").textContent=Number(m.median_latency_ms).toFixed(1);$("#consistencyMetric").innerHTML=(m.consistency_violations?"—":"100<sup>%</sup>")}
function renderSessions(){const body=$("#sessionsBody"),empty=$("#emptySessions");body.innerHTML=sessions.map(s=>`<tr><td><strong>${escapeHtml(s.source_ip)}</strong><small>${escapeHtml(s.username)}@${escapeHtml(s.hostname)}</small></td><td>${escapeHtml(s.persona)}</td><td><span class="tag ${s.profile.automation.label==='automated'?'hot':''}">${escapeHtml(s.profile.automation.label)}</span></td><td><span class="tag">${escapeHtml(s.profile.objective.label.replaceAll('_',' '))}</span></td><td><strong>${s.command_count}</strong></td><td><button class="row-open" data-id="${s.id}">Inspect →</button></td></tr>`).join("");empty.style.display=sessions.length?"none":"block";document.querySelectorAll(".row-open").forEach(b=>b.onclick=()=>selectSession(b.dataset.id))}
async function selectSession(id){selected=id;const d=await api(`/api/sessions/${id}`),s=d.state,p=d.profile;$("#profileTitle").textContent=`${s.username}@${s.persona.hostname}`;$("#profileContent").className="profile-bars";$("#profileContent").innerHTML=[["Automation",p.automation],["Sophistication",p.sophistication],["Objective",p.objective]].map(([n,x])=>`<div class="profile-row"><div class="profile-label"><span>${n} · <b>${escapeHtml(x.label.replaceAll('_',' '))}</b></span><span>${Math.round(x.confidence*100)}%</span></div><div class="bar"><i style="width:${x.confidence*100}%"></i></div><div class="reason">${escapeHtml(x.evidence[0]||'Gathering additional evidence')}</div></div>`).join("");const unique=[...new Map(d.techniques.map(x=>[x.technique_id,x])).values()];$("#evidenceCount").textContent=`${unique.length} mapped`;$("#evidenceList").innerHTML=unique.length?unique.map(x=>`<div class="evidence-item"><span class="tech-id">${x.technique_id}</span><div><strong>${escapeHtml(x.name)}</strong><small>${escapeHtml(x.status.replaceAll('_',' '))} · ${escapeHtml(x.explanation)}</small></div><span class="confidence">${Math.round(x.confidence*100)}%</span></div>`).join(""):'<div class="profile-empty">No techniques mapped yet.</div>';$("#terminalHost").textContent=`adaptive shell · ${s.persona.hostname}`;$("#prompt").textContent=`${s.username}@${s.persona.hostname}:${shortPath(s.cwd)}$`;$("#commandInput").disabled=false;$("#commandInput").placeholder="Enter a safe virtual command";$("#commandInput").focus();if(!$("#terminalOutput").dataset.session||$("#terminalOutput").dataset.session!==id){$("#terminalOutput").dataset.session=id;$("#terminalOutput").innerHTML=d.events.length?d.events.map(eventMarkup).join(""):'<p class="muted"># Connected. Try: uname -a, ls -la, cat /etc/os-release</p>'}}
const shortPath=p=>p.startsWith('/home/')?p.replace(/^\/home\/[^/]+/,'~'):p;
function eventMarkup(e){return `<p class="cmd">${escapeHtml(e.cwd_before)} $ ${escapeHtml(e.command)}</p>${e.response.stdout?`<p>${escapeHtml(e.response.stdout)}</p>`:''}${e.response.stderr?`<p class="err">${escapeHtml(e.response.stderr)}</p>`:''}${e.deception?.applied?`<p class="muted"># policy: ${escapeHtml(e.deception.action)}</p>`:''}`}
$("#newSession").onclick=()=>$("#sessionDialog").showModal();$("#createSession").onclick=async e=>{e.preventDefault();try{const d=await api("/api/sessions",{method:"POST",body:JSON.stringify({persona_id:$("#persona").value,source_ip:$("#sourceIp").value,username:"deploy"})});$("#sessionDialog").close();selected=d.state.id;await load();toast("Isolated session created")}catch(err){toast(err.message)}};
$("#refresh").onclick=load;$("#clearTerminal").onclick=()=>$("#terminalOutput").innerHTML='<p class="muted"># Terminal cleared. Evidence log is unchanged.</p>';
$("#terminalForm").onsubmit=async e=>{e.preventDefault();const input=$("#commandInput"),command=input.value.trim();if(!command||!selected)return;input.value="";input.disabled=true;try{const d=await api(`/api/sessions/${selected}/commands`,{method:"POST",body:JSON.stringify({command})});$("#terminalOutput").insertAdjacentHTML("beforeend",eventMarkup(d.event));$("#terminalOutput").scrollTop=$("#terminalOutput").scrollHeight;$("#prompt").textContent=`${d.state.username}@${d.state.persona.hostname}:${shortPath(d.state.cwd)}$`;await load()}catch(err){toast(err.message)}finally{input.disabled=false;input.focus()}};
try{const ws=new WebSocket(`${location.protocol==='https:'?'wss':'ws'}://${location.host}/ws/sessions`);ws.onmessage=()=>load()}catch{}
load();

